# Generated by Django 6.0.4 on 2026-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='category',
        ),
        migrations.AddField(
            model_name='costume',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='costumes', to='catalogue.category'),
        ),
    ]
