# Generated by Django 6.0.6 on 2026-07-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_costume_category_costume_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='costume',
            options={'ordering': ['name'], 'verbose_name': 'Kostium', 'verbose_name_plural': 'Kostiumy'},
        ),
        migrations.AlterModelOptions(
            name='costumeimage',
            options={'ordering': ['-is_main', 'id'], 'verbose_name': 'Zdjęcie kostiumu', 'verbose_name_plural': 'Zdjęcia kostiumów'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name': 'Rozmiar', 'verbose_name_plural': 'Rozmiary'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tagi'},
        ),
    ]
