# Generated by Django 6.0.3 on 2026-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('read', 'Przeczytane'), ('replied', 'Odpowiedziano')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, related_name='inquiries', to='catalogue.costume')),
            ],
            options={
                'verbose_name': 'Zapytanie',
                'verbose_name_plural': 'Zapytania',
                'ordering': ['-created_at'],
            },
        ),
    ]
